version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  gosec:
    excludes:
      - G104
      - G115
